<center>
	<table>
		<tr>
			<td height="200">&nbsp;</td>
		</tr>
		<tr>
			<td>
				<fieldset>
					<legend>$MandatoryCommitedFsHeading</legend>
						<table>
							<tr>
								<td>$MandatoryCommited</td>
							</tr>
							<tr>
								<td>$MandatoryCommitedLink</td>
							</tr>
						</table>
				</fieldset>
			</td>
		</tr>
	</table>
</center>		